[build]
  publish = "."

[[redirects]]
  from = "/submit.html"
  to = "/submit.html"
  status = 200

[[redirects]]
  from = "/submit-success.html"
  to = "/submit-success.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
